"""Agent-wide constants.

## Model Configuration
- MODEL_NAME: Gemini model identifier used for both the routing agent and
  SQL generation. Change this single value to switch models globally.

## Database Table Mapping
- CSV_TABLE_MAP: Ordered mapping of CSV filenames to SQLite table names.
  Ordered by foreign-key dependencies for safe loading.

## SQL Safety
- FORBIDDEN_SQL_PATTERNS: Regex patterns used to reject non-SELECT SQL
  statements generated by the LLM.
- SQL_RESULT_LIMIT: Default LIMIT appended to queries that lack one,
  preventing runaway result sets.
"""

import re


### Model configuration

MODEL_NAME: str = "gemini-2.5-flash"

### SQL safety

FORBIDDEN_SQL_PATTERNS: re.Pattern[str] = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|REPLACE)\b",
    re.IGNORECASE,
)

SQL_RESULT_LIMIT: int = 100

### Agent configuration

AGENT_NAME: str = "portfolio_agent"